### ISSUE TITLE
cant get pass the  door login

### ISSUE THREAD

**Issue by FreakyPlory** [a9fm/bkebi-repack#1]
![image](https://user-images.githubusercontent.com/127558401/226028622-d3a08862-b500-4905-a06e-a416916ffdfe.png)

**Comment by a9fm** [comment]
edit cfg.ini, and edit to this


[System]
InitializationDelayMS = 25000

if you catch this error away, try writte value high

[System]
InitializationDelayMS = 50000


i use:

[System]
InitializationDelayMS = 120000
